datasource:
  default: ${APP_ENV}
  development:
    username: sa
    password: sa
    url: "jdbc:h2:./hexlet"
  production:
    username: "postgres"
    password: "postgres"
    url: "jdbc:postgresql://172.20.127.90:5432/hexlet_db"

# Заполняем базу данных первоначальными данными
ebean:
  db:
    ddl:
      generate: true
      run: true
      seedSql: seed.sql