datasource:
  default: ${APP_ENV}
  development:
    username: ""
    password: ""
    url: "jdbc:h2:./hexlet;AUTO_SERVER=TRUE"
  production:
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}
  local_pg:
    username: "postgres"
    password: "postgres"
    url: "jdbc:postgresql://172.19.209.225:5432/hexletdb"

## запуск миграционных скриптов /resources/dbmigration после старта Ebean сервера
ebean:
  migration:
    run: true